/// Reference data shared by test targets.
///
/// Lives in its own module rather than in a test target because more than one test target needs
/// it, and because a fixture that is duplicated drifts. It holds data only: assertions stay in
/// the test targets, since SwiftPM links the testing library into those alone.
public enum PercentileFixture {
    /// One hundred frame durations in nanoseconds, deliberately unsorted and containing
    /// duplicates and one long outlier.
    ///
    /// Nearest-rank percentiles over this vector are stated below. They are computed by hand
    /// from the definition, not by the code under test — a fixture generated by the
    /// implementation it checks proves only that the implementation is consistent with itself.
    public static let frameDurationsNs: [UInt64] = {
        var values: [UInt64] = []
        values.reserveCapacity(100)
        // 1...100 scaled to a plausible frame-time range, then perturbed into a realistic shape:
        // a tight body around 8 ms and a tail that a mean would hide and a p99 will not.
        for index in 1...96 {
            values.append(UInt64(7_600_000 + index * 10_000))
        }
        values.append(contentsOf: [21_000_000, 24_500_000, 31_000_000, 48_000_000])
        return values
    }()

    /// Expected nearest-rank percentiles of ``frameDurationsNs``, in nanoseconds.
    ///
    /// Nearest-rank with `ceil(p/100 * n)` on `n = 100`: p50 is the 50th smallest, p95 the 95th,
    /// p99 the 99th.
    public static let expectedP50Ns: UInt64 = 8_100_000
    public static let expectedP95Ns: UInt64 = 8_550_000
    public static let expectedP99Ns: UInt64 = 31_000_000
    public static let expectedMaxNs: UInt64 = 48_000_000
}
